<a href="https://colab.research.google.com/github/Xaviera8/Github.Test/blob/main/clean1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Cleaning With Pandas

## Import Packages

In [16]:
import pandas as pd
import re
import os

##Load the Data set

In [10]:
df = pd.read_csv('healthcare_data_cleaning.csv')
df

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889
1,25,Female,East Jocelynfurt,Colorado,No,Yes,Card,Dr. Johnson,Flu,Med_B,Specialist,59,missing,174,58,430.68365678679174,195,missing,4,80.78647284463952
2,51,Other,South Lindseyland,Ohio,Yes,No,Cash,Dr. Williams,Covid-19,Med_D,General,79,119,161,56,315.0709305262176,missing,37,2,64.3921393009105
3,18,Female,Taylorfort,Pennsylvania,Yes,missing,Cash,Dr. Williams,Flu,Med_A,General,99,115,171,52,320.2998987723972,175,108,2,8.872859215315316
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7533,33,Male,New Shellymouth,Wyoming,Yes,Yes,Insurance,Dr. Brown,Allergy,Med_B,missing,87,80,183,84,226.4471902762724,170,13,3,2.2131188118218406
7534,21,Female,South Heidiside,Kansas,Yes,No,Cash,Dr. Jones,Cold,Med_E,Follow-Up,91,104,182,80,120.13330217772533,missing,31,6,17.192382290925785
7535,35,Female,Port Crystal,Georgia,No,Yes,Insurance,Dr. Johnson,Allergy,Med_D,Specialist,79,100,182,79,363.4918420988218,197,49,3,117.28664722575695
7536,65,Other,Jamesport,Massachusetts,missing,Yes,Insurance,Dr. Jones,None,Med_C,Emergency,85,103,168,104,313.51372552331105,175,34,4,70.04721860670035
7537,55,Female,North Robert,missing,No,Yes,missing,Dr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##Check for any missing values in the dataset

In [11]:
print(df.isnull().sum())

Patient Age              0
Gender                   0
City of Residence        0
State of Residence       0
Has Insurance            0
Visited Last Month       0
Payment Method           0
Preferred Doctor         0
Disease Diagnosed        1
Medication Prescribed    1
Type of Appointment      1
Average Heart Rate       1
Average BP               1
Height (in cm)           1
Weight (in kg)           1
Payment Due ($)          1
Last Visit (days ago)    1
Visit Duration (mins)    1
Number of Tests          1
Prescription Cost ($)    1
dtype: int64

## Remove any missing values from the dataset

In [60]:
df.dropna(inplace=True)
print(df.isnull().sum())

Patient_Age              0
Gender                   0
City_of_Residence        0
State_of_Residence       0
Has_Insurance            0
Visited_Last_Month       0
Payment_Method           0
Preferred_Doctor         0
Disease_Diagnosed        0
Medication_Prescribed    0
Type_of_Appointment      0
Average_Heart_Rate       0
Average_BP               0
Height_(in_cm)           0
Weight_(in_kg)           0
Payment_Due_($)          0
Last_Visit_(days_ago)    0
Visit_Duration_(mins)    0
Number_of_Tests          0
Prescription_Cost_($)    0
Weight Group             0
Weight Group in KG       0
dtype: int64

## Remove any duplicate rows and columns, if they exist

In [22]:
df.drop_duplicates(inplace=True)
df

,Patient_Age,Gender,City_of_Residence,State_of_Residence,Has_Insurance,Visited_Last_Month,Payment_Method,Preferred_Doctor,Disease_Diagnosed,Medication_Prescribed,Type_of_Appointment,Average_Heart_Rate,Average_BP,Height_(in_cm),Weight_(in_kg),Payment_Due_($),Last_Visit_(days_ago),Visit_Duration_(mins),Number_of_Tests,Prescription_Cost_($)
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889
1,25,Female,East Jocelynfurt,Colorado,No,Yes,Card,Dr. Johnson,Flu,Med_B,Specialist,59,missing,174,58,430.68365678679174,195,missing,4,80.78647284463952
2,51,Other,South Lindseyland,Ohio,Yes,No,Cash,Dr. Williams,Covid-19,Med_D,General,79,119,161,56,315.0709305262176,missing,37,2,64.3921393009105
3,18,Female,Taylorfort,Pennsylvania,Yes,missing,Cash,Dr. Williams,Flu,Med_A,General,99,115,171,52,320.2998987723972,175,108,2,8.872859215315316
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7533,33,Male,New Shellymouth,Wyoming,Yes,Yes,Insurance,Dr. Brown,Allergy,Med_B,missing,87,80,183,84,226.4471902762724,170,13,3,2.2131188118218406
7534,21,Female,South Heidiside,Kansas,Yes,No,Cash,Dr. Jones,Cold,Med_E,Follow-Up,91,104,182,80,120.13330217772533,missing,31,6,17.192382290925785
7535,35,Female,Port Crystal,Georgia,No,Yes,Insurance,Dr. Johnson,Allergy,Med_D,Specialist,79,100,182,79,363.4918420988218,197,49,3,117.28664722575695
7536,65,Other,Jamesport,Massachusetts,missing,Yes,Insurance,Dr. Jones,None,Med_C,Emergency,85,103,168,104,313.51372552331105,175,34,4,70.04721860670035
7537,55,Female,North Robert,missing,No,Yes,missing,Dr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Clean Colums Names????

In [15]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(' ', '_')
df

,Patient_Age,Gender,City_of_Residence,State_of_Residence,Has_Insurance,Visited_Last_Month,Payment_Method,Preferred_Doctor,Disease_Diagnosed,Medication_Prescribed,Type_of_Appointment,Average_Heart_Rate,Average_BP,Height_(in_cm),Weight_(in_kg),Payment_Due_($),Last_Visit_(days_ago),Visit_Duration_(mins),Number_of_Tests,Prescription_Cost_($)
0,45,Other,West Brian,Kentucky,Yes,Yes,Insurance,Dr. Williams,Flu,Med_E,General,66,111,183,70,65.45721578126224,193,92,5,15.71751735532889
1,25,Female,East Jocelynfurt,Colorado,No,Yes,Card,Dr. Johnson,Flu,Med_B,Specialist,59,missing,174,58,430.68365678679174,195,missing,4,80.78647284463952
2,51,Other,South Lindseyland,Ohio,Yes,No,Cash,Dr. Williams,Covid-19,Med_D,General,79,119,161,56,315.0709305262176,missing,37,2,64.3921393009105
3,18,Female,Taylorfort,Pennsylvania,Yes,missing,Cash,Dr. Williams,Flu,Med_A,General,99,115,171,52,320.2998987723972,175,108,2,8.872859215315316
4,48,Female,Birdmouth,Montana,No,No,Insurance,Dr. Brown,None,Med_C,Specialist,93,89,186,87,264.2147372473319,188,113,3,77.48311304645532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7533,33,Male,New Shellymouth,Wyoming,Yes,Yes,Insurance,Dr. Brown,Allergy,Med_B,missing,87,80,183,84,226.4471902762724,170,13,3,2.2131188118218406
7534,21,Female,South Heidiside,Kansas,Yes,No,Cash,Dr. Jones,Cold,Med_E,Follow-Up,91,104,182,80,120.13330217772533,missing,31,6,17.192382290925785
7535,35,Female,Port Crystal,Georgia,No,Yes,Insurance,Dr. Johnson,Allergy,Med_D,Specialist,79,100,182,79,363.4918420988218,197,49,3,117.28664722575695
7536,65,Other,Jamesport,Massachusetts,missing,Yes,Insurance,Dr. Jones,None,Med_C,Emergency,85,103,168,104,313.51372552331105,175,34,4,70.04721860670035
7537,55,Female,North Robert,missing,No,Yes,missing,Dr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#

#Data Transformation

## Create new columns based on existing ones (e.g., if you have a 'birth_date' column, create an 'age' column).

In [25]:
df.columns

Index(['Patient_Age', 'Gender', 'City_of_Residence', 'State_of_Residence',
       'Has_Insurance', 'Visited_Last_Month', 'Payment_Method',
       'Preferred_Doctor', 'Disease_Diagnosed', 'Medication_Prescribed',
       'Type_of_Appointment', 'Average_Heart_Rate', 'Average_BP',
       'Height_(in_cm)', 'Weight_(in_kg)', 'Payment_Due_($)',
       'Last_Visit_(days_ago)', 'Visit_Duration_(mins)', 'Number_of_Tests',
       'Prescription_Cost_($)'],
      dtype='object')

## Aggregate data using groupby and compute summary statistics.

In [48]:
df['Weight_(in_kg)'] = pd.to_numeric(df['Weight_(in_kg)'], errors='coerce')
df['Weight_(in_kg)'].fillna(df['Weight_(in_kg)'].median(), inplace=True)


grouped_data = df.groupby('State_of_Residence').agg({
    'Weight_(in_kg)': ['mean']  # Average Age
})
print(grouped_data)

                   Weight_(in_kg)
                             mean
State_of_Residence
Alabama                 69.957746
Alaska                  67.598425
Arizona                 68.600000
Arkansas                68.890625
California              69.310976
Colorado                69.316547
Connecticut             70.014388
Delaware                68.865854
Florida                 70.912409
Georgia                 69.429752
Hawaii                  70.512821
Idaho                   68.780347
Illinois                69.817460
Indiana                 68.827068
Iowa                    69.428571
Kansas                  70.311111
Kentucky                70.213333
Louisiana               68.124138
Maine                   69.860656
Maryland                70.111111
Massachusetts           69.918239
Michigan                68.564103
Minnesota               69.604027
Mississippi             68.152000
Missouri                68.980519
Montana                 70.000000
Nebraska                69.775362
Nevada                  69.941860
New Hampshire           69.016260
New Jersey              68.773006
New Mexico              71.215827
New York                67.544715
North Carolina          69.939850
North Dakota            68.230303
Ohio                    70.407407
Oklahoma                70.251852
Oregon                  67.357143
Pennsylvania            67.694030
Rhode Island            71.029412
South Carolina          67.557047
South Dakota            69.595588
Tennessee               70.080000
Texas                   68.472441
Utah                    70.458015
Vermont                 69.597403
Virginia                68.651163
Washington              69.457516
West Virginia           69.762590
Wisconsin               70.062016
Wyoming                 69.421429
missing                 70.282723

## Use Pivot Tables or Cross Tabulations for Multidimensional Analysis

In [72]:

df['Weight Group in KG'] = pd.cut(
    df['Weight_(in_kg)'],
    bins = (66, 68, 70, 72),
    labels = ['66 - 68', '68 - 70', '70 - 72']
)

pivottable = df.pivot_table(index = 'Weight Group in KG', columns = 'Gender', values ='Patient_Age', aggfunc = 'mean' )

print (pivottable)

Gender                 Female       Male      Other    missing
Weight Group in KG
66 - 68             67.547368  67.567308  67.555556  67.411765
68 - 70             69.255230  69.239837  69.279070  69.263158
70 - 72             71.512397  71.564516  71.488189  71.409091

# Introduction to Alternative Libraries

## Load the dataset using Polars and Modin

In [102]:
import polars as pl
import time

polarstart = time.time()

polardf = pl.read_csv('healthcare_data_cleaning.csv')
polardf

polartotal = time.time() - polarstart
print (polartotal)

0.01579737663269043

In [106]:
pip install modin

Collecting modin
  Downloading modin-0.23.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.3 MB/s eta 0:00:00
Collecting pandas<2.1,>=2 (from modin)
  Downloading pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 29.9 MB/s eta 0:00:00
Requirement already satisfied: packaging>=21.0 in /usr/local/lib/python3.10/dist-packages (from modin) (23.1)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.10/dist-packages (from modin) (1.23.5)
Requirement already satisfied: fsspec>=2021.07.0 in /usr/local/lib/python3.10/dist-packages (from modin) (2023.6.0)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from modin) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<2.1,>=2->modin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.1,>=2->modin) (2023.3.post1)
Collecting tzdata>=2022.1 (from pandas<2.1,>=2->modin)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 33.7 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<2.1,>=2->modin) (1.16.0)
Installing collected packages: tzdata, pandas, modin
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.
Successfully installed modin-0.23.1 pandas-2.0.3 tzdata-2023.3

In [105]:
import modin.pandas as mpd

modinstart = time.time()

modindf = pl.read_csv('healthcare_data_cleaning.csv')
modindf

modintotal = time.time() - modinstart
print (modintotal)

SyntaxError: ignored